// ---------- Settings ----------
const WHATSAPP_NUMBER = "60148359886";
// PHOTOS comes from photos.js (generated by update-gallery.js)

// ---------- Gallery page ----------
const grid = document.getElementById("grid");
if (grid) {
  const box = document.getElementById("lightbox");
  const big = document.getElementById("big");
  PHOTOS.forEach(p => {
    const tile = document.createElement("button");
    tile.className = "tile";
    tile.setAttribute("aria-label", "View " + p.title);
    const img = new Image();
    img.src = p.src; img.alt = p.title; img.loading = "lazy";
    tile.appendChild(img);
    tile.addEventListener("click", () => {
      big.src = p.src; big.alt = p.title;
      box.classList.add("open");
    });
    grid.appendChild(tile);
  });
  const close = () => box.classList.remove("open");
  document.getElementById("close").addEventListener("click", close);
  box.addEventListener("click", e => { if (e.target === box) close(); });
  document.addEventListener("keydown", e => { if (e.key === "Escape") close(); });
}

// ---------- Contact page: booking -> WhatsApp ----------
const send = document.getElementById("send");
if (send) {
  send.addEventListener("click", () => {
    const v = id => document.getElementById(id).value.trim();
    const error = document.getElementById("error");
    if (!v("name") || !v("date")) {
      error.textContent = "Enter your name and graduation date to continue.";
      return;
    }
    error.textContent = "";
    const msg =
      "Hi, I'd like to book a graduation photo session.\n" +
      "Name: " + v("name") + "\n" +
      "Date: " + v("date") + "\n" +
      "Package: " + v("pkg") + "\n" +
      (v("venue") ? "Venue: " + v("venue") + "\n" : "") +
      (v("notes") ? "Notes: " + v("notes") : "");
    window.open("https://wa.me/" + WHATSAPP_NUMBER + "?text=" + encodeURIComponent(msg), "_blank");
  });
}

// ---------- Home page: buttons fade in as you start scrolling ----------
const heroActions = document.querySelector(".hero-actions");
if (heroActions) {
  const SHOW_AFTER = 20;     // pixels scrolled before the buttons start to appear
  const FULL_AT = 220;       // pixels scrolled when they are fully visible
  function fadeButtons() {
    const p = Math.min(Math.max((window.scrollY - SHOW_AFTER) / (FULL_AT - SHOW_AFTER), 0), 1);
    heroActions.style.opacity = p;
    heroActions.style.pointerEvents = p > 0.3 ? "auto" : "none";
  }
  window.addEventListener("scroll", fadeButtons, { passive: true });
  fadeButtons();
}
