// Auto-generated by update-gallery.js. Do not edit by hand.
const PHOTOS = [
  {
    "src": "images/grad1.jpg",
    "title": "Graduation portrait 1"
  },
  {
    "src": "images/grad2.jpg",
    "title": "Graduation portrait 2"
  },
  {
    "src": "images/grad3.jpg",
    "title": "Graduation portrait 3"
  },
  {
    "src": "images/grad4.jpg",
    "title": "Graduation portrait 4"
  },
  {
    "src": "images/grad5.jpg",
    "title": "Graduation portrait 5"
  },
  {
    "src": "images/grad6.jpg",
    "title": "Graduation portrait 6"
  }
];
