// Auto-generated by update-gallery.js. Do not edit by hand.
const PHOTOS = [
  {
    "src": "images/( _drniating ) __ brightest smile ever 💕(JPG).jpg",
    "title": "(  Drniating )   Brightest Smile Ever 💕(JPG)"
  },
  {
    "src": "images/( _gee_akb ) __ _shell_malaysia pls hire him(JPG)_1.jpg",
    "title": "(  Gee Akb )    Shell Malaysia Pls Hire Him(JPG) 1"
  },
  {
    "src": "images/grad1.jpg",
    "title": "Grad1"
  },
  {
    "src": "images/grad2.jpg",
    "title": "Grad2"
  },
  {
    "src": "images/grad3.jpg",
    "title": "Grad3"
  },
  {
    "src": "images/grad4.jpg",
    "title": "Grad4"
  },
  {
    "src": "images/grad5.jpg",
    "title": "Grad5"
  },
  {
    "src": "images/grad6.jpg",
    "title": "Grad6"
  }
];
