// Run:  node update-gallery.js
// Scans the images/ folder and rewrites photos.js so every photo appears in the gallery.
const fs = require("fs");
const path = require("path");

const DIR = "images";
const EXCLUDE = /^hero\./i;               // images that should NOT be in the gallery
const EXT = /\.(jpe?g|png|webp|gif|avif)$/i;

const title = f =>
  path.parse(f).name.replace(/[-_]+/g, " ").replace(/\b\w/g, c => c.toUpperCase());

const files = fs.readdirSync(path.join(__dirname, DIR))
  .filter(f => EXT.test(f) && !EXCLUDE.test(f))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const photos = files.map(f => ({ src: `${DIR}/${f}`, title: title(f) }));

fs.writeFileSync(
  path.join(__dirname, "photos.js"),
  "// Auto-generated by update-gallery.js. Do not edit by hand.\nconst PHOTOS = " +
    JSON.stringify(photos, null, 2) + ";\n"
);
console.log(`photos.js updated: ${photos.length} photos`);


